"""add display order column

Revision ID: 572dcaa838e9
Revises: ee8823c4113d
Create Date: 2025-01-14 19:00:15.257422

"""
from alembic import op # type: ignore
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '572dcaa838e9'
down_revision = 'ee8823c4113d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add display_order column to both tables
    op.add_column('item_number', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('receiving_data', sa.Column('display_order', sa.Integer(), nullable=True))
    
    # Initialize display_order based on current order
    conn = op.get_bind()
    conn.execute(text("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) as rn
            FROM item_number
        )
        UPDATE item_number 
        SET display_order = ranked.rn
        FROM ranked
        WHERE item_number.id = ranked.id
    """))
    
    conn.execute(text("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) as rn
            FROM receiving_data
        )
        UPDATE receiving_data 
        SET display_order = ranked.rn
        FROM ranked
        WHERE receiving_data.id = ranked.id
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_number', 'display_order')
    op.drop_column('receiving_data', 'display_order')

    # ### end Alembic commands ###
