"""Add ON DELETE SET NULL to user FKs

Revision ID: 82a6a6a8564c
Revises: f32df3737540
Create Date: 2025-04-17 16:23:46.956540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a6a6a8564c'
down_revision = 'f32df3737540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_number', schema=None) as batch_op:
        batch_op.drop_constraint('item_number_created_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('item_number_updated_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('receiving_data', schema=None) as batch_op:
        batch_op.drop_constraint('receiving_data_updated_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('receiving_data_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('receiving_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('receiving_data_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('receiving_data_updated_by_fkey', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('item_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('item_number_updated_by_fkey', 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key('item_number_created_by_fkey', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
