"""Add Status and registration date column to users table

Revision ID: 8a040f0ccf3a
Revises: 572dcaa838e9
Create Date: 2025-02-25 21:17:14.365288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a040f0ccf3a'
down_revision = '572dcaa838e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_number', schema=None) as batch_op:
        batch_op.alter_column('is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('receiving_data', schema=None) as batch_op:
        batch_op.alter_column('is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registration_date')
        batch_op.drop_column('status')

    with op.batch_alter_table('receiving_data', schema=None) as batch_op:
        batch_op.alter_column('is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('item_number', schema=None) as batch_op:
        batch_op.alter_column('is_obsolete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
