"""initial migration

Revision ID: ceeb61de3c15
Revises: 18629a71e680
Create Date: 2025-01-09 23:11:16.757508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeb61de3c15'
down_revision = '18629a71e680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('protocol_number', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False),
    sa.Column('controlled', sa.String(length=50), nullable=False),
    sa.Column('temp_storage_conditions', sa.String(length=50), nullable=False),
    sa.Column('other_storage_conditions', sa.String(length=50), nullable=True),
    sa.Column('max_exposure_time', sa.Integer(), nullable=True),
    sa.Column('temper_time', sa.Integer(), nullable=True),
    sa.Column('working_exposure_time', sa.Integer(), nullable=True),
    sa.Column('vendor_code_rev', sa.String(length=50), nullable=False),
    sa.Column('randomized', sa.String(length=10), nullable=False),
    sa.Column('sequential_numbers', sa.String(length=10), nullable=False),
    sa.Column('study_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_number')
    )
    op.create_table('receiving_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('receiving_no', sa.String(length=20), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('lot_no', sa.String(length=50), nullable=True),
    sa.Column('po_no', sa.String(length=50), nullable=True),
    sa.Column('total_units_vendor', sa.Integer(), nullable=True),
    sa.Column('total_storage_containers', sa.Integer(), nullable=True),
    sa.Column('exp_date', sa.Date(), nullable=True),
    sa.Column('ncmr', sa.String(length=5), nullable=True),
    sa.Column('total_units_received', sa.Integer(), nullable=True),
    sa.Column('temp_device_in_alarm', sa.String(length=20), nullable=True),
    sa.Column('ncmr2', sa.String(length=5), nullable=True),
    sa.Column('temp_device_deactivated', sa.String(length=5), nullable=True),
    sa.Column('temp_device_returned_to_courier', sa.String(length=5), nullable=True),
    sa.Column('comments_for_520b', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_number'], ['item_number.item_number'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiving_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiving_data')
    op.drop_table('item_number')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
