"""add obsolete column

Revision ID: ee8823c4113d
Revises: ceeb61de3c15
Create Date: 2025-01-14 14:05:03.371149

"""
from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8823c4113d'
down_revision = 'ceeb61de3c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_number', sa.Column('is_obsolete', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('receiving_data', sa.Column('is_obsolete', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_number', 'is_obsolete')
    op.drop_column('receiving_data', 'is_obsolete')

    # ### end Alembic commands ###
